CREATE OR REPLACE TABLE `<TABLE_NAME_PARTITIONED_CLUSTERED>` 
PARTITION BY 
  TIMESTAMP_TRUNC(TIME, HOUR) 
CLUSTER BY 
  PRODUCT_ID AS
select TYPE, PRODUCT_ID, CHANGE_SIDE, CHANGE_PRICE, CHANGE_SIZE, TIMESTAMP(TIME) as TIME
from `<TABLE_NAME>`
;
